# Generated by Django 5.2.3 on 2025-06-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('НОВАЯ', 'новая'), ('ПОДТВЕРЖДЕННАЯ', 'подтвержденная'), ('ОТМЕНЕННАЯ', 'отмененная'), ('ВЫПОЛЕННАЯ', 'выполненная')], default='not_approved', max_length=50, verbose_name='Статус'),
        ),
    ]
