# Generated by Django 5.2.3 on 2025-06-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={'ordering': ['name'], 'verbose_name': 'Мастер', 'verbose_name_plural': 'Список Мастеров'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['appointment_date'], 'verbose_name': 'Запись', 'verbose_name_plural': 'Список записей'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['master'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Список отзывов'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['description'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Список услуг'},
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[('УЖАСНО', 'Ужасно'), ('ПЛОХО', 'Плохо'), ('НОРМАЛЬНО', 'Нормально'), ('ХОРОШО', 'Хорошо'), ('ОТЛИЧНО', 'Отлично')], verbose_name='Оценка'),
        ),
    ]
