# Generated by Django 5.2.3 on 2025-06-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='photo',
            field=models.ImageField(blank=True, upload_to='masters_images/', verbose_name='Фотография'),
        ),
    ]
