# Generated by Django 5.2.3 on 2025-07-05 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_master_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={'ordering': ['name'], 'verbose_name': 'Мастера', 'verbose_name_plural': 'Список Мастеров'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['description'], 'verbose_name': 'Услугу', 'verbose_name_plural': 'Список услуг'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('НОВАЯ', 'новая'), ('ПОДТВЕРЖДЕННАЯ', 'подтвержденная'), ('ОТМЕНЕННАЯ', 'отмененная'), ('ВЫПОЛЕННАЯ', 'выполненная')], default='НОВАЯ', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='review',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.master', verbose_name='Мастер'),
        ),
    ]
